
name: Build AutoIt3 binaries
run-name: Build version ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the library
        required: true
        default: 0.1.0
        type: string
      release:
        description: Create a release
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install AutoIt3
      run: |
        $Setup = "autoit-v3-setup.exe"
        $Uri = "https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/$Setup"
        Invoke-WebRequest -Uri $Uri -OutFile $Setup
        & .\$Setup /S
    - name: Install SciTE4AutoIt3
      run: |
        $Setup2 = "SciTE4AutoIt3.exe"
        $Uri2 = "https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/$Setup2"
        Invoke-WebRequest -Uri $Uri2 -OutFile $Setup2
        & .\$Setup2 /S
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile AutoIt3 files
      run: |
        $Aut2exe = "C:\Program Files (x86)\AutoIt3\Aut2exe\Aut2exe.exe"
        $Icon = "app.ico"
        New-Item -Type Directory -Name _build
        & $Aut2exe /in LaunchAppContainer.au3 /out _build\LaunchAppContainer.exe /nopack /icon $Icon /comp 2 /x64
        & $Aut2exe /in LearningMode.au3 /out _build\LearningMode.exe /nopack /icon $Icon /comp 2 /x64
        & $Aut2exe /in SetAppContainerACL.au3 /out _build\SetAppContainerACL.exe /nopack /icon $Icon /comp 2 /x64
    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: executable-files
        path: |
          _build
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.release }}
      with:
        draft: true
        files: |
          _build/LaunchAppContainer.exe
          _build/LearningMode.exe
          _build/SetAppContainerACL.exe
